# To better understand this file read this:
# https://docs.ionos.space/docs/github-actions-customization/

name: "Deploy Now: Execute Build"

on:
  workflow_call:
    inputs:
      site-url:
        required: true
        type: string
      branch-id:
        required: true
        type: string

env:
  DEPLOYMENT_FOLDER: dist

jobs:
# Please do not rename this job
  build-project:
    name: build ai-tool
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: v20.x

      - name: Build Node assets
        env:
          CI: true
          SITE_URL: ${{ inputs.site-url }}
          VITE_OCTOAI_TOKEN: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjNkMjMzOTQ5In0.eyJzdWIiOiJiNjkxYTdhMC0wYzZkLTRjOWEtYTU1Ny02YjdlZDZiY2RkYTYiLCJ0eXBlIjoidXNlckFjY2Vzc1Rva2VuIiwidGVuYW50SWQiOiI0ZTE5OTUyMi04NGYzLTQxMWItYjAxOS05NDFiZmQxOTM5ZGIiLCJ1c2VySWQiOiIwNjkwN2Y0ZC0zYzEwLTRkOTUtOWQ1MC0wYTE2ZDkxMGZkYWUiLCJyb2xlcyI6WyJGRVRDSC1ST0xFUy1CWS1BUEkiXSwicGVybWlzc2lvbnMiOlsiRkVUQ0gtUEVSTUlTU0lPTlMtQlktQVBJIl0sImF1ZCI6IjNkMjMzOTQ5LWEyZmItNGFiMC1iN2VjLTQ2ZjYyNTVjNTEwZSIsImlzcyI6Imh0dHBzOi8vaWRlbnRpdHkub2N0b21sLmFpIiwiaWF0IjoxNzExNjU4Mjc4fQ.rhqm2_Dc8mcYkRFZ2mHA5lAuChxWOKY0G6HWx4rsG0QVPWRXSmIg-J4S27Cve92iVExFgLBzfHnEHdt68Q-XSo-Aboy4Fzs8Oj3TwSxQJZFRMVlgXgMU_7OesTPD_rb0S9iSylssIIWfB2MZQkH3TayKB7ZM1WIt2dCATpRR4bePnCnhhi_ZdjIHqvAjVtJ3EbJM525wVPXjsPEQ3WJTKOtOd4fGeLBV3uOiDtAGu3lREVp0h-0kq_KsHtSwfCIW5Si761w4HBUFAmZ7UJeMyLyYJOUk3l4T_AylghwMV1-j2Q-ydXPkoSiooA6K_wnfBNRvn9RwtK13e7Q5c9Bd9g
        run: |
          npm ci
          npm run build

# Please do not touch the following action
      - name: Store deployment content
        uses: ionos-deploy-now/artifact-action@v1
        with:
          api-key: ${{ secrets.IONOS_API_KEY }}
          service-host: api-eu.ionos.space
          project-id: c7a53a73-bf05-4f9b-82bb-7a0064929c88
          branch-id: ${{ inputs.branch-id }}
          version: ${{ github.sha }}
          folder: ${{ env.DEPLOYMENT_FOLDER }}
          config-file: .deploy-now/ai-tool/config.yaml
          action: upload
